services:
  discord-bot:
    image: ghcr.io/dexythepuppy/verflauschigungfotogalerie:latest
    # Or use Docker Hub format:
    # image: yourusername/discord-image-bot:latest
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
      DISCORD_LOG_CHANNEL_ID: ${DISCORD_LOG_CHANNEL_ID}
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - discord-data:/app/data
    restart: unless-stopped

volumes:
  discord-data:
    driver: local 