services:
  discord-bot:
    image: ghcr.io/dexythepuppy/verflauschigungfotogalerie:latest
    # Or use Docker Hub format:
    # image: yourusername/discord-image-bot:latest
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
    volumes:
      - discord-data:/app/image-list.json
    restart: unless-stopped

volumes:
  discord-data:
    external: true 