services:
  discord-bot:
    image: ghcr.io/dexythepuppy/verflauschigungfotogalerie:latest
    # Or use Docker Hub format:
    # image: yourusername/discord-image-bot:latest
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CHANNEL_ID: ${DISCORD_CHANNEL_ID}
      DISCORD_LOG_CHANNEL_ID: ${DISCORD_LOG_CHANNEL_ID}
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data  # Use bind mount to local directory
    user: "1000:1000"  # Use explicit UID/GID
    restart: unless-stopped
    networks:
      - bot-network

volumes:
  discord-data:
    external: true  # Use existing volume

networks:
  bot-network:
    driver: bridge 