services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-image-bot
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
    volumes:
      - ./image-list.json:/app/image-list.json
    restart: unless-stopped 